export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const UPDATE_TOTALPRICE = 'UPDATE_TOTALPRICE';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENT_PRICES = 'SET_INGREDIENTPRICES';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const FETCH_INGREDIENT_PRICES_FAILED = 'FETCH_INGREDIENT_PRICES_FAILED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_INIT= 'PURCHASE_INIT';